### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fewtarius** [Rose22/es-theme-minielec#1]
Hi @Rose22, is this theme licensed for redistribution?  Is it copyleft?  It doesn't appear to have any visible license applied, so I thought I'd check.

Thanks!

**Comment by Rose22** [comment]
oh, oops, im new to that! what license does it need to enable that? i'd love for it to be included in retro cfw's!

**Comment by fewtarius** [comment]
> oh, oops, im new to that! what license does it need to enable that? i'd love for it to be included in retro cfw's!

No worries! :)

Since this is a theme and not an application, I would recommend taking a look at [https://creativecommons.org/share-your-work/](https://creativecommons.org/share-your-work/) and choosing the license that best suits you.  You can apply it to your repository by creating LICENSE.md in the root of your project and pasting the license content into it, and/or by including the license metadata in your README.md.

**Comment by Rose22** [comment]
> > oh, oops, im new to that! what license does it need to enable that? i'd love for it to be included in retro cfw's!
> 
> No worries! :)
> 
> Since this is a theme and not an application, I would recommend taking a look at https://creativecommons.org/share-your-work/ and choosing the license that best suits you. You can apply it to your repository by creating LICENSE.md in the root of your project and pasting the license content into it, and/or by including the license metadata in your README.md.

thanks! done. does it allow you to do what you need to?

**Comment by fewtarius** [comment]
This is perfect, thank you. :)
